### ISSUE TITLE
[Python3] Drumsets won't switch

### ISSUE THREAD

**Issue by Wohlstand** [adambiser/imf-creator#13]
Trying to play different drumsets doesn't work properly

[XG tests.zip](https://github.com/adambiser/imf-creator/files/4076440/XG.tests.zip)

When you using drums, you should use patch change event as a drum bank choice (from 0 to 127)

**Comment by adambiser** [comment]
Correct now?

**Comment by Wohlstand** [comment]
Will test at my home, right now I am in path

**Comment by Wohlstand** [comment]
Okay, now it works, however, another problem: 
Because the "MidiChannelInfo"'s "instrument" is `None` by default, an error may happen when playing a MIDI file without any patch set:
[Alternative 174 - 1-4 note kick.mid.zip](https://github.com/adambiser/imf-creator/files/4081697/Alternative.174.-.1-4.note.kick.mid.zip)

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/vitaly/_git_repos/imf-creator/imfcreator/__main__.py", line 324, in <lambda>
    self.settings.song_file.trace_add("write", lambda *_: self.reload_midi_song())
  File "/home/vitaly/_git_repos/imf-creator/imfcreator/__main__.py", line 384, in reload_midi_song
    self._convert_song()
  File "/home/vitaly/_git_repos/imf-creator/imfcreator/__main__.py", line 393, in _convert_song
    self._adlib_song = AdlibSongFile.convert_from(self._midi_song, self.settings.filetype.get())
  File "/home/vitaly/_git_repos/imf-creator/imfcreator/plugins/__init__.py", line 344, in convert_from
    return filetype_class._convert_from(midi_song, filetype, settings)
  File "/home/vitaly/_git_repos/imf-creator/imfcreator/plugins/imffileplugin.py", line 446, in _convert_from
    engine.start()
  File "/home/vitaly/_git_repos/imf-creator/imfcreator/plugins/_midiengine.py", line 108, in start
    self.on_note_on(song_event=NoteEvent(**event_args))
  File "/home/vitaly/_git_repos/imf-creator/imfcreator/signal.py", line 39, in __call__
    self.trigger(*args, **kwargs)
  File "/home/vitaly/_git_repos/imf-creator/imfcreator/signal.py", line 36, in trigger
    listener(**kwargs)
  File "/home/vitaly/_git_repos/imf-creator/imfcreator/plugins/imffileplugin.py", line 334, in on_note_on
    instrument = get_event_instrument(song_event.channel, song_event.note)
  File "/home/vitaly/_git_repos/imf-creator/imfcreator/plugins/imffileplugin.py", line 258, in get_event_instrument
    return instruments.get(InstrumentType.PERCUSSION, midi_channel.instrument, note)
  File "/home/vitaly/_git_repos/imf-creator/imfcreator/instruments.py", line 87, in get
    _validate_args(inst_type, bank, program)
  File "/home/vitaly/_git_repos/imf-creator/imfcreator/instruments.py", line 131, in _validate_args
    if bank < 0 or bank > 16383:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
A quick fix is replacing `= None` with `= 0`. I think this should always default rather than dealing with `None` here.

**Comment by adambiser** [comment]
Fixed.  I notice a bunch of "Note out of range: -4" errors on these songs.
Is this due to given note / note offset not handled correctly, or is it due bad instrument settings?

EDIT: I still wanted the "unassigned" warning, so I changed instrument to a property that will set None to 0 internally before returning.

**Comment by adambiser** [comment]
While looking through your code to see how you handle instruments with both a given note and an offset, I noticed this:

https://github.com/Wohlstand/libADLMIDI/blob/master/src/adlmidi_midiplay.cpp#L338
size_t bank = (midiChan.bank_msb * 256) + midiChan.bank_lsb;

I think you want 128 instead of 256 there.

**Comment by Wohlstand** [comment]
> I notice a bunch of "Note out of range: -4" errors on these songs.

It's because of note offsets in a bank. In libADLMIDI/libOPNMIDI, note offset is converting into pitch offset which is adding to the final pitch in a hertz formula:
https://github.com/Wohlstand/libADLMIDI/blob/master/src/adlmidi_midiplay.cpp#L1360-L1373

Applying note offset to the MIDI key is not a good solution because it limits an ability to play the sound out of MIDI key range which chip can play.

Note that the note offset in the code here has the `ins.ains.finetune` name in semitones. The final value is computing in semitones and then converting into OPL3's hertz after.

**Comment by adambiser** [comment]
OK, so the note offset is applied correctly, given the underlying note/freq lookup method.  It's just that the note/freq lookup can be better.  Something for a later day.

**Comment by Wohlstand** [comment]
> I think you want 128 instead of 256 there.

I use 256 to keep all data from events:
![изображение](https://user-images.githubusercontent.com/6751442/72671381-638eec00-3a5a-11ea-9756-4008910a5c87.png)
I keep all data came from MIDI that allows me to process them more accurate and don't lose anything. Using 128 isn't good and it's literally lossy. In libADLMIDI is implemented the SysEx system that can toggle GS / GM and XG modes (and also it allows to set drum channels via SysEx as GS likes to do), and this also affects the bank change formula that makes GS songs be played correctly and allows them to identify each bank number accurately.

**Comment by Wohlstand** [comment]
If you'll look the code lower, you'll find the code that does this computation for each case. All banks inside of libADLMIDI/libOPNMIDI are indexing by `(msb<<8) +  lsb` formula to keep the key simple. This allows having 65536 melodic banks and 128 melodic banks maximum.

**Comment by Wohlstand** [comment]
Anyway, speaking about extended frequency, I left an issue #14 as it's out of this topic

**Comment by adambiser** [comment]
OK.  I had read the comments mentioning 16128 and 16256 and misinterpreted.

**Comment by Wohlstand** [comment]
>  16128 and 16256 and misinterpreted.

That because of Cakewalk Sonar 1.3 (I have used for my music works) inside self prints inside self, I left these notes here. There are just absolute codes of specific mode, they aren't minimal/maximal range means. In fact, these values should be unsigned. Old Sonar (and old Cakewalk software) is pretty stupid or makes something "friendly" which confused me for tens of years until I became a programmer and I learned that much deeper.

**Comment by adambiser** [comment]
The latest Bandlab Cakewalk says the same because those are the MIDI values using 7 bit shift.
https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2

So GS goes outside of the MIDI spec?  I'm not familiar with it.

**Comment by Wohlstand** [comment]
Then I see that there are `0...127` values are. I made the use of `(msb<<8) + lsb` internally as it's easier to compute. GS does the use of bank's MSB in most, however, the LSB is taken for a using to specify the difference of some bank sets between SC55, SC88, SC88Pro synths, and usually should have a fallback to the lsb=0. I had some trouble with this which has been fixed later with a cooperated work with @jpcima, @papiezak, and @sneakernets who helped to research this problem.

**Comment by adambiser** [comment]
I guess it really doesn't matter which is used as long as it's consistent.  Not an issue unless the song expects to use a bank above 16383.

I did make a commit to adjust for SFX banks, but forgot to tag it with this issue number.  Does the percussion bank/instrument patch stuff check out now?

**Comment by Wohlstand** [comment]
I did the test, and yeah, it works fine :fox_face: :+1: 
Anything if I'll find later, I'll notice :wink:
