### ISSUE TITLE
Make sure key offs were added into end of file

### ISSUE THREAD

**Issue by Wohlstand** [adambiser/imf-creator#15]
I have an example of music:
[tmarsh.zip](https://github.com/adambiser/imf-creator/files/5523197/tmarsh.zip)

When it looks, notes aren't off, and the next cycle causes them to sound persistent until those channels will be re-used again. I guess you should always add key offs at end of the track for all channels to prevent such mess.

**Comment by adambiser** [comment]
These messages are at the end of the imf in your zip file:
B1 16 00 00 
B2 12 00 00 
B3 0B 00 00 
B4 0A 00 00 
B5 06 00 00 
B6 16 00 00 
B7 0E 00 00
These are note-offs for all channels.

There are checks in imffileplugin to see whether the input song or generated song have any open notes and those warnings don't show up for this song.  What do you use to listen to the song?

**Comment by Wohlstand** [comment]
Okay, that is a confirmation that it's a bug of my player... Yes! That was a bug that messes up the entire last row because of zero delays.

I fixed that by adding of next lines:
https://github.com/Wohlstand/libADLMIDI/blob/master/src/midi_sequencer_impl.hpp#L2257-L2260

Thank you for help to figure out the fact it was my bug! :fox_face:
