### ISSUE TITLE
Unexpected note sticking at one of channels

### ISSUE THREAD

**Issue by Wohlstand** [adambiser/imf-creator#19]
Hello!

At 2/3 of the song, one of the voices got stuck and stay sounding until the end of the song.
[ievan_polkka2.zip](https://github.com/adambiser/imf-creator/files/6107686/ievan_polkka2.zip)
Using `Apogee-IMF-90.wopl` bank.
That happens very rarely and on specific songs. This song I made using Cakewalk Sonar 1.3, I used another MIDI file as a base.

**Comment by adambiser** [comment]
This is happening because of this sequence in measure 47 on MIDI channel 0.
NOTE_ON -> PROGRAM_CHANGE -> NOTE_OFF
The note and instrument are used to find the note to shut off, so when the instrument change happens while the note is playing, it can no longer find it.

Looking into how to resolve the issue.

**Comment by Wohlstand** [comment]
I have some:
- when you put the Note ON at the MIDI channel, remember it's the last instrument separately
- when you put the Note OFF at the same MIDI channel, re-use the last remembered instrument
- when playing a new note, use the new instrument
However, there are chords that can be here, so, each currently playing note should have a copy of the last-playing instrument.

At me in libADLMIDI and libOPNMIDI for every playing MIDI note the array entry called "active notes" adds. It has the MIDI channel, its setup, and the chip hardware channel used to play the note. It gets used to shut up the note when it gets off with no matter instrument changes at the MIDI channel. The actual instrument change happens together with the note ON at the hardware channel.

**Comment by adambiser** [comment]
That's essentially what I'm trying out.  Each channel in the MIDI engine already has an active note list.  I'm just seeing what it takes to include the instrument as well without breaking things.

**Comment by adambiser** [comment]
This should be fixed now.  I've restructured some of the code and moved the active note management stuff into the midiengine where it belongs.

**Comment by Wohlstand** [comment]
Tested just now, thanks a lot! :fox_face: :+1:
