### ISSUE TITLE
Attempt to save IMF file leads error

### ISSUE THREAD

**Issue by Wohlstand** [adambiser/imf-creator#21]
Recently I updated the thing, and attempted to save the IMF file, however, I got the next error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/vitaly/_git_repos_contrib/imf-creator/imfcreator/__main__.py", line 478, in save_adlib_song
    "filetypes": [(self._adlib_song.filetype_description, f"*.{self._adlib_song.default_extension}"),
  File "/home/vitaly/_git_repos_contrib/imf-creator/imfcreator/plugins/__init__.py", line 301, in filetype_description
    return next([ft.description for ft in self._get_filetypes() if ft.name == self._filetype], None)
TypeError: 'list' object is not an iterator
```

Can't debug it right now because I am busy, will try in the evening...

Files I used:
- [Drunken Sailor_synstr.mid.zip](https://github.com/adambiser/imf-creator/files/8589414/Drunken.Sailor_synstr.mid.zip)
- [d3dtimbr-modded-2op.wopl.zip](https://github.com/adambiser/imf-creator/files/8589421/d3dtimbr-modded-2op.wopl.zip)

My system:
- Linux Mint 20.3
- python 3.8.10

**Comment by adambiser** [comment]
Easy fix.  Will post later

**Comment by adambiser** [comment]
Should be fixed now.

**Comment by Wohlstand** [comment]
Confirm, it works! :+1:
