### ISSUE TITLE
Unstable tempo on some songs

### ISSUE THREAD

**Issue by Wohlstand** [adambiser/imf-creator#6]
While processing some songs, I hear that they would suddenly go faster or slower than usually.
One of example songs with unstable tempo: [Ecu_10_Bass_xg-hr.zip](https://github.com/adambiser/imf-creator/files/3851334/Ecu_10_Bass_xg-hr.zip)
I see that all delays are rounding by casting into `int()` which isn't good way. What the solution? Instead of casting all delays into `int()`, we should align time positions to fit them into certan ticks rate (700, 560, 280) and keep tempo go stable.

**Comment by adambiser** [comment]
It's not the rounding, per se, but rather compounding the rounding that causes the speed issues.  This is fixed in the Python 3 code I'm preparing.

**Comment by Wohlstand** [comment]
Okay, once the branch is here, I have tested it, and... it works! Thanks! :fox_face:
